name: Build 
on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Echo
        run: echo ${{ github.ref_name }}