name: Build 
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

concurrency:
  group: ci-${{ inputs.tag }}
  cancel-in-progress: true

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Echo
        run: echo ${{ inputs.tag }}
