name: Release Please

on:
  push:
    branches:
      - 'main'
      - 'release-please--branches--**'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-please-${{ github.ref_name }}

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build trainer
        if: steps.release.outputs.release_created == 'true'
        uses: ./.github/workflows/build.yml
        with:
          tag: ${{ steps.release.outputs.tag_name }}





      # - name: Notify Mattermost
      #   if: steps.release.outputs.release_created == 'true'
      #   run: |

      #     payload=$(cat <<EOF
      #     {
      #     "attachments": [
      #         {
      #         "color": "#9bb7f3",
      #         "title": "Новая сборка тренера",
      #         "text": "New release ${{ steps.release.outputs.tag_name }}\nhttps://github.com/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag_name }}\n\n${{ steps.release.outputs.body }}"
      #         }
      #     ]
      #     }
      #     EOF
      #     )

      #     curl -X POST -H 'Content-Type: application/json' \
      #       -d "$payload" \
      #       ${{ secrets.MATTERMOST_WEBHOOK_URL }}
